---
- name: AS3 BIG-IP declaration
  hosts: localhost
  connection: local
  gather_facts: no

  vars:

  vars_files:
  - ../credentials/bigip_credentials.yaml

  tasks:
  - name: Deploy AS3 to BIG-IP
    uri:
      url: https://51.142.10.142:8443/mgmt/shared/appsvcs/declare
      user: "{{bigip_user}}"
      password: "{{bigip_pass}}"
      method: POST
      body: "{{ lookup('file','./as3.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: false
    register: as3_output

  - name: DEBUG
    debug:
      msg: "AS3 OUTPUT {{as3_output}}"  

...